import { Job, ReportTextOverrides } from './types'

export function getDefaultTexts(job: Job): ReportTextOverrides {
  return {
    coverNote:
      `Note: There is no charge for this report which has taken professional time and effort to create. All we ask is that if ever you decide to proceed in the future, you give us the opportunity to re-quote against anyone else you may engage with.\n\nThe price quoted herein includes full installation and project management.\n\nPlease note that although we calculate what the correct lux levels will be with a fair amount of accuracy, at any stage when we have to increase the quantity of luminaires to achieve a higher lux level, this is for the client's account. Any faulty wiring, conduit, fittings or plug points which need replacing will be invoiced as a separate cost to the client.\n\nOur costings are based on the quantities on the initial count. There can be inaccuracies and any changes will be subject to discussion with the client and ultimately for the client's account.`,

    letterPara1:
      `Thank you for the opportunity to do a Lighting Energy Efficiency Audit of your facility based on the light quantities as required. Please be aware that the calculations attached are mathematical calculations and although they should be very accurate, there might be some variances caused by a tariff variance or the number of hours being incorrect. We have taken the cost of electricity from your electricity account, used the hours your staff have said your lamps are burning and taken the wattages of your current installation and placed them in a spreadsheet which uses straightforward mathematics to calculate the numbers.`,

    letterPara2:
      `We have used energy-saving technology which we view to be most suitable throughout. Quality of product and lifespan is important to us as we want the technology to have reliability and longevity. The LED luminaires we recommend are always 60,000 working hours and above.`,

    letterMaintTitle: `Savings which will have a substantial effect but not included:`,

    letterMaintPoints:
      `No maintenance or purchase of lights for at least 3 years. No maintenance teams to pay. This frees maintenance staff up to attend to other machinery.\nNo budget expenditure on lights for at least 3 years.\nCarbon Tax when it is implemented.`,

    letterTariffComment:
      `Eskom has been awarded increases to recover losses from corruption and loopholes in the MYPD (Multi-Year Price Determination) rules by increasing your tariffs by an estimated ${job.eskomIncrease}% annually. Each successive increase amplifies the return on this investment — the savings generated by LED fittings grow year on year. This report includes a 10-year financial projection incorporating the applicable Eskom escalation rate so that you can see the compounding benefit over time.`,

    overviewPoints:
      `The current view has been replaced in the report with energy-savings globes and fittings on an estimated requirement basis.\nWe have allowed for new fittings.\nWe highly recommend the removal of current lights.\nThe warranty offered is a full 3-year replacement carry-in uninstalled. It is the duty of the client's maintenance department to change out any faulty lights. We have not in 12 years experienced very many faulty products; such is the quality of the luminaires used.\nThe reduction in electricity on this report is substantial per annum.\nPlease note that although we calculate what the correct lux levels will be with a fair amount of accuracy, at any stage when we have to increase the quantity of luminaires to achieve a higher lux level, this is for the client's account.\nEskom tariff escalation of ${job.eskomIncrease}% per annum has been used in all financial projections.\nWe do not profit from the installation cost. We pass on these costs directly.`,
  }
}
